#spring.application.name=Data_JPA_App_03
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sandeepdb
    username: root
    password: Admin@123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true