#spring.application.name=Data_JPA_App_01
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sandeepdb
    username: root
    password: Admin@123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create